CREATE SEQUENCE users_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS Users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(20),
    language VARCHAR(10),
    verification_token VARCHAR(255),
    reset_token VARCHAR(255),
    is_verified BOOLEAN DEFAULT FALSE,
    token_expiration_date TIMESTAMP
);

CREATE SEQUENCE coverages_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS Coverages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coverage_name VARCHAR(100) NOT NULL
);

CREATE SEQUENCE neighborhoods_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS Neighborhoods (
                                             id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             name VARCHAR(30) NOT NULL
    );

CREATE TABLE IF NOT EXISTS patients (
    patient_id INTEGER PRIMARY KEY,
    coverage_id INTEGER NOT NULL,
    neighborhood_id INTEGER NOT NULL,
    FOREIGN KEY (neighborhood_id) REFERENCES Neighborhoods(id) ON DELETE RESTRICT,
    FOREIGN KEY (patient_id) REFERENCES Users(id) ON DELETE CASCADE,
    FOREIGN KEY (coverage_id) REFERENCES Coverages(id)
);

CREATE SEQUENCE images_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS Images (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image BLOB NOT NULL,
);

CREATE TABLE IF NOT EXISTS Doctors (
    doctor_id INTEGER PRIMARY KEY,
    rating FLOAT,
    rating_count INTEGER,
    image_id INT,
    FOREIGN KEY (doctor_id) REFERENCES Users(id) ON DELETE CASCADE,
    FOREIGN KEY (image_id) REFERENCES Images(id) ON DELETE SET NULL,
    CHECK (rating >= 1 AND rating <= 5)
);

CREATE TABLE IF NOT EXISTS Doctor_Coverages (
    doctor_id INTEGER NOT NULL,
    coverage_id INTEGER NOT NULL,
    PRIMARY KEY (doctor_id, coverage_id),
    FOREIGN KEY (doctor_id) REFERENCES Doctors(doctor_id) ON DELETE CASCADE,
    FOREIGN KEY (coverage_id) REFERENCES Coverages(id) ON DELETE CASCADE
);

CREATE SEQUENCE specialties_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS Specialties (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS Doctor_Specialties (
    doctor_id INTEGER NOT NULL,
    specialty_id INTEGER NOT NULL,
    PRIMARY KEY (doctor_id, specialty_id),
    FOREIGN KEY (doctor_id) REFERENCES Doctors(doctor_id) ON DELETE CASCADE,
    FOREIGN KEY (specialty_id) REFERENCES Specialties(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Doctor_Availability (
    doctor_id INTEGER NOT NULL,
    day_of_week INTEGER NOT NULL, -- 0 = Monday, 6 = Sunday
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    PRIMARY KEY (doctor_id, day_of_week, start_time),
    FOREIGN KEY (doctor_id) REFERENCES Doctors(doctor_id) ON DELETE CASCADE
);

CREATE SEQUENCE appointments_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS Appointments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_id INTEGER NOT NULL,
    patient_id INTEGER NOT NULL,
    specialty_id INTEGER NOT NULL,
    date TIMESTAMP NOT NULL,
    status VARCHAR(20) DEFAULT 'confirmado' NOT NULL,
    reason VARCHAR(10000),
    report VARCHAR(10000),
    office_id INTEGER NOT NULL,
    allow_full_history BOOLEAN NOT NULL,
    FOREIGN KEY (doctor_id) REFERENCES Doctors(doctor_id) ON DELETE CASCADE,
    FOREIGN KEY (patient_id) REFERENCES patients(patient_id) ON DELETE CASCADE,
    FOREIGN KEY (specialty_id) REFERENCES Specialties(id) ON DELETE CASCADE,
    CHECK (status IN ('confirmado','cancelado', 'completo'))
);

CREATE SEQUENCE ratings_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS Ratings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_id INTEGER NOT NULL,
    patient_id INTEGER NOT NULL,
    appointment_id INTEGER NOT NULL UNIQUE,
    rating INTEGER,
    comment VARCHAR(10000),
    FOREIGN KEY (doctor_id) REFERENCES Doctors(doctor_id) ON DELETE CASCADE,
    FOREIGN KEY (patient_id) REFERENCES patients(patient_id) ON DELETE CASCADE,
    FOREIGN KEY (appointment_id) REFERENCES Appointments(id) ON DELETE CASCADE,
    CHECK (rating >= 1 AND rating <= 5)
);

CREATE SEQUENCE appointment_files_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS appointment_files (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id INTEGER NOT NULL,
    uploader_role VARCHAR(20) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_data BLOB NOT NULL,
    FOREIGN KEY (appointment_id) REFERENCES Appointments(id) ON DELETE CASCADE
);

CREATE SEQUENCE doctor_offices_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS Doctor_Offices (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_id INTEGER NOT NULL,
    neighborhood_id INTEGER NOT NULL,
    office_name VARCHAR(50) NOT NULL,
    active BOOLEAN DEFAULT TRUE NOT NULL ,
    removed TIMESTAMP,
    UNIQUE (doctor_id, neighborhood_id, office_name, removed),
    FOREIGN KEY (doctor_id) REFERENCES Doctors(doctor_id) ON DELETE CASCADE,
    FOREIGN KEY (neighborhood_id) REFERENCES Neighborhoods(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS Doctor_Unavailability (
    doctor_id INT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    PRIMARY KEY (doctor_id, start_date, end_date),
    FOREIGN KEY (doctor_id) REFERENCES Doctors(doctor_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Doctor_Office_Specialties (
    office_id INT NOT NULL,
    specialty_id INT NOT NULL,
    PRIMARY KEY (office_id, specialty_id),
    FOREIGN KEY (office_id) REFERENCES Doctor_Offices(id) ON DELETE CASCADE,
    FOREIGN KEY (specialty_id) REFERENCES Specialties(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Doctor_Profile (
    doctor_id INT PRIMARY KEY,
    bio VARCHAR(1000),
    description VARCHAR(1000),
    FOREIGN KEY (doctor_id) REFERENCES Doctors(doctor_id) ON DELETE CASCADE
);

CREATE SEQUENCE doctor_experience_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS Doctor_Experience (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_id INT NOT NULL,
    position_title VARCHAR(100) NOT NULL,
    organization_name VARCHAR(100) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    description VARCHAR(1000),
    FOREIGN KEY (doctor_id) REFERENCES Doctors(doctor_id) ON DELETE CASCADE
);

CREATE SEQUENCE doctor_certification_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS Doctor_Certifications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_id INT NOT NULL,
    certificate_name VARCHAR(100) NOT NULL,
    issuing_entity VARCHAR(100) NOT NULL,
    issue_date DATE NOT NULL,
    FOREIGN KEY (doctor_id) REFERENCES Doctors(doctor_id) ON DELETE CASCADE
);