-- Creación de Tablas para hsql --

CREATE TABLE IF NOT EXISTS Users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(20),
    language VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS Coverages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coverage_name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Clients (
    client_id INTEGER PRIMARY KEY,
    coverage_id INTEGER NOT NULL,
    FOREIGN KEY (client_id) REFERENCES Users(id) ON DELETE CASCADE,
    FOREIGN KEY (coverage_id) REFERENCES Coverages(id)
);

CREATE TABLE IF NOT EXISTS Doctors (
    doctor_id INTEGER PRIMARY KEY,
    rating FLOAT,
    rating_count INTEGER,
    FOREIGN KEY (doctor_id) REFERENCES Users(id) ON DELETE CASCADE,
    CHECK (rating >= 1 AND rating <= 5)
);

CREATE TABLE IF NOT EXISTS Doctor_Coverages (
    doctor_id INTEGER NOT NULL,
    coverage_id INTEGER NOT NULL,
    PRIMARY KEY (doctor_id, coverage_id),
    FOREIGN KEY (doctor_id) REFERENCES Doctors(doctor_id) ON DELETE CASCADE,
    FOREIGN KEY (coverage_id) REFERENCES Coverages(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Specialties (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS Doctor_Specialties (
    doctor_id INTEGER NOT NULL,
    specialty_id INTEGER NOT NULL,
    PRIMARY KEY (doctor_id, specialty_id),
    FOREIGN KEY (doctor_id) REFERENCES Doctors(doctor_id) ON DELETE CASCADE,
    FOREIGN KEY (specialty_id) REFERENCES Specialties(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Doctor_Availability (
    doctor_id INTEGER NOT NULL,
    day_of_week INTEGER NOT NULL, -- 0 = Monday, 6 = Sunday
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    PRIMARY KEY (doctor_id, day_of_week, start_time),
    FOREIGN KEY (doctor_id) REFERENCES Doctors(doctor_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Appointments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_id INTEGER NOT NULL,
    client_id INTEGER NOT NULL,
    specialty_id INTEGER NOT NULL,
    date TIMESTAMP NOT NULL,
    status VARCHAR(20) NOT NULL,
    reason VARCHAR(10000),
    FOREIGN KEY (doctor_id) REFERENCES Doctors(doctor_id) ON DELETE CASCADE,
    FOREIGN KEY (client_id) REFERENCES Clients(client_id) ON DELETE CASCADE,
    FOREIGN KEY (specialty_id) REFERENCES Specialties(id) ON DELETE CASCADE,
    CHECK (status IN ('confirmado','cancelado'))
);

CREATE TABLE IF NOT EXISTS Images (
    doctor_id INTEGER PRIMARY KEY,
    image BLOB NOT NULL,
    FOREIGN KEY (doctor_id) REFERENCES Doctors(doctor_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Reviews (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_id INTEGER NOT NULL,
    client_id INTEGER NOT NULL,
    appointment_id INTEGER NOT NULL UNIQUE,
    rating INTEGER,
    comment VARCHAR(10000),
    FOREIGN KEY (doctor_id) REFERENCES Doctors(doctor_id) ON DELETE CASCADE,
    FOREIGN KEY (client_id) REFERENCES Clients(client_id) ON DELETE CASCADE,
    FOREIGN KEY (appointment_id) REFERENCES Appointments(id) ON DELETE CASCADE,
    CHECK (rating >= 1 AND rating <= 5)
);

CREATE TABLE IF NOT EXISTS appointment_files (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id INTEGER NOT NULL,
    uploader_role VARCHAR(20) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_data BLOB NOT NULL,
    FOREIGN KEY (appointment_id) REFERENCES Appointments(id) ON DELETE CASCADE
);

-- Población de Tablas para hsql --

INSERT INTO Users (id, name, last_name, email, password, phone, language)
VALUES (1, 'John', 'Doe', 'john@example.com', 'hashedpassword', '123456789', 'en'),
       (2, 'Jane', 'Smith', 'jane@example.com', 'hashedpassword', '987654321', 'es');

INSERT INTO Coverages (id, coverage_name)
VALUES (1, 'Coverage A'), (2, 'Coverage B');

INSERT INTO Clients (client_id, coverage_id)
VALUES (1, 1);

INSERT INTO Doctors (doctor_id, rating, rating_count)
VALUES (2, 4.5, 10);

INSERT INTO Doctor_Coverages (doctor_id, coverage_id)
VALUES (2, 1);

INSERT INTO Specialties (id, key)
VALUES (1, 'Cardiology'),
       (2, 'Neurology'),
       (3, 'Orthopedics');

INSERT INTO Doctor_Specialties (doctor_id, specialty_id)
VALUES (2, 1);

INSERT INTO Doctor_Availability (doctor_id, day_of_week, start_time, end_time)
VALUES (2, 0, '09:00:00', '12:00:00');

INSERT INTO Appointments (id, doctor_id, client_id, specialty_id, date, status, reason)
VALUES (1, 2, 1, 1, '2025-04-29 10:00:00', 'confirmado', 'Consulta general');

INSERT INTO Images (doctor_id, image)
VALUES (2, X'00');

INSERT INTO Reviews (id, doctor_id, client_id, appointment_id, rating, comment)
VALUES (1, 2, 1, 1, 5, 'Excelente atención');

INSERT INTO appointment_files (id, appointment_id, uploader_role, file_name, file_data)
VALUES (1, 1, 'doctor', 'informe.pdf', X'00');
