CREATE TABLE IF NOT EXISTS Users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(20),
    language VARCHAR(10),
    verification_token VARCHAR(255),
    reset_token VARCHAR(255),
    is_verified BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS Coverages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coverage_name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Clients (
    client_id INTEGER PRIMARY KEY,
    coverage_id INTEGER NOT NULL,
    FOREIGN KEY (client_id) REFERENCES Users(id) ON DELETE CASCADE,
    FOREIGN KEY (coverage_id) REFERENCES Coverages(id)
);

CREATE TABLE IF NOT EXISTS Images (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image BLOB NOT NULL,
);

CREATE TABLE IF NOT EXISTS Doctors (
    doctor_id INTEGER PRIMARY KEY,
    rating FLOAT,
    rating_count INTEGER,
    image_id INT,
    FOREIGN KEY (doctor_id) REFERENCES Users(id) ON DELETE CASCADE,
    FOREIGN KEY (image_id) REFERENCES Images(id) ON DELETE SET NULL,
    CHECK (rating >= 1 AND rating <= 5)
);

CREATE TABLE IF NOT EXISTS Doctor_Coverages (
    doctor_id INTEGER NOT NULL,
    coverage_id INTEGER NOT NULL,
    PRIMARY KEY (doctor_id, coverage_id),
    FOREIGN KEY (doctor_id) REFERENCES Doctors(doctor_id) ON DELETE CASCADE,
    FOREIGN KEY (coverage_id) REFERENCES Coverages(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Specialties (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS Doctor_Specialties (
    doctor_id INTEGER NOT NULL,
    specialty_id INTEGER NOT NULL,
    PRIMARY KEY (doctor_id, specialty_id),
    FOREIGN KEY (doctor_id) REFERENCES Doctors(doctor_id) ON DELETE CASCADE,
    FOREIGN KEY (specialty_id) REFERENCES Specialties(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Doctor_Availability (
    doctor_id INTEGER NOT NULL,
    day_of_week INTEGER NOT NULL, -- 0 = Monday, 6 = Sunday
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    PRIMARY KEY (doctor_id, day_of_week, start_time),
    FOREIGN KEY (doctor_id) REFERENCES Doctors(doctor_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Appointments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_id INTEGER NOT NULL,
    client_id INTEGER NOT NULL,
    specialty_id INTEGER NOT NULL,
    date TIMESTAMP NOT NULL,
    status VARCHAR(20) DEFAULT 'confirmado' NOT NULL,
    reason VARCHAR(10000),
    report VARCHAR(10000),
    FOREIGN KEY (doctor_id) REFERENCES Doctors(doctor_id) ON DELETE CASCADE,
    FOREIGN KEY (client_id) REFERENCES Clients(client_id) ON DELETE CASCADE,
    FOREIGN KEY (specialty_id) REFERENCES Specialties(id) ON DELETE CASCADE,
    CHECK (status IN ('confirmado','cancelado', 'completo'))
);

CREATE TABLE IF NOT EXISTS Ratings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_id INTEGER NOT NULL,
    client_id INTEGER NOT NULL,
    appointment_id INTEGER NOT NULL UNIQUE,
    rating INTEGER,
    comment VARCHAR(10000),
    FOREIGN KEY (doctor_id) REFERENCES Doctors(doctor_id) ON DELETE CASCADE,
    FOREIGN KEY (client_id) REFERENCES Clients(client_id) ON DELETE CASCADE,
    FOREIGN KEY (appointment_id) REFERENCES Appointments(id) ON DELETE CASCADE,
    CHECK (rating >= 1 AND rating <= 5)
);

CREATE TABLE IF NOT EXISTS appointment_files (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id INTEGER NOT NULL,
    uploader_role VARCHAR(20) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_data BLOB NOT NULL,
    FOREIGN KEY (appointment_id) REFERENCES Appointments(id) ON DELETE CASCADE
);
