<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>

<!DOCTYPE html>
<html>
<head>
    <link rel="icon" type="image/png" href="https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/V-logo.svg/2048px-V-logo.svg.png" />
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><spring:message code="dashboard.availability.title" /></title>
    <link rel="stylesheet" href="<c:url value='/css/doctor-dashboard.css' />" />
    <link rel="stylesheet" href="<c:url value='/css/toast-notification.css' />" />
    <link rel="stylesheet" href="<c:url value='/css/unavailability-calendar.css' />" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
</head>
<body>
<!-- Include the header -->
<jsp:include page="/WEB-INF/jsp/components/header.jsp">
    <jsp:param name="id" value="${doctor.imageId}" />
    <jsp:param name="doctorId" value="${doctor.id}" />
</jsp:include>

<div id="successToast" class="success-toast">
    <div class="success-toast-icon">
        <i class="fas fa-check"></i>
    </div>
    <div class="success-toast-content">
        <div class="success-toast-title"><spring:message code="profile.update.success.title"/></div>
        <div class="success-toast-message"><spring:message code="profile.update.success.message"/></div>
    </div>
    <button class="success-toast-close" onclick="hideSuccessToast()">
        <i class="fas fa-times"></i>
    </button>
</div>

<main class="dashboard-container">

    <c:set var="activeTab" value="availability" scope="request" />
    <c:set var="user" value="${doctor}" scope="request"/>
    <c:set var="isDoctor" value="${true}" scope="request"/>
    <jsp:include page="/WEB-INF/jsp/components/dashboard-header.jsp"/>

    <!-- Dashboard Content Area -->
    <div class="dashboard-content">
        <div class="tab-content active" id="availability-tab">
            <div class="tab-header">
                <h2><spring:message code="dashboard.availability.title" /></h2>
            </div>

            <div class="profile-content">
                <!-- Unified Form for both Availability and Unavailability -->
                <form:form id="updateAvailabilityForm" modelAttribute="updateAvailabilityForm" method="post" action="${pageContext.request.contextPath}/doctor/dashboard/availability/update" cssClass="edit-profile-form">
                    <form:hidden path="doctorId"/>
                    <!-- Availability Slots Section -->
                    <div class="profile-section">
                        <h3 class="section-title">
                            <i class="fas fa-calendar-alt"></i>
                            <spring:message code="dashboard.availability.currentSlots" />
                        </h3>

                        <div id="trash-warning-availability" class="warning-message" style="display: none; margin-top: 10px;">
                            <i class="fas fa-exclamation-triangle"></i>
                            <span><spring:message code="dashboard.availability.trashWarning" /></span>
                        </div>

                        <div id="timeslots-container" class="timeslots-container">
                            <div id="no-slots-message" class="no-slots-message" style="${empty doctorOfficesAvailability ? '' : 'display: none;'}">
                                <p><spring:message code="dashboard.availability.noTimeSlots" /></p>
                            </div>

                            <div id="time-slot-inputs">
                                <!-- Time slots will be dynamically generated by JavaScript -->
                            </div>

                            <div id="time-slot-error" class="error-message" style="display: none; margin-bottom: 10px;"></div>
                            <div class="error-container">
                                <form:errors path="doctorOfficeAvailabilitySlots" cssClass="error-message" element="div" />
                            </div>

                            <button type="button" class="btn-add-slot" onclick="addTimeSlotRow()">
                                <i class="fas fa-plus"></i> <spring:message code="dashboard.availability.addTimeSlot" />
                            </button>
                        </div>
                    </div>

                    <h3 class="section-title">
                        <i class="fas fa-calendar-alt"></i>
                        <spring:message code="dashboard.availability.unavailabilityDates" />
                    </h3>
                    <div id="trash-warning-unavailability" class="warning-message" style="display: none; margin-top: 10px;">
                        <i class="fas fa-exclamation-triangle"></i>
                        <span><spring:message code="dashboard.availability.trashWarning" /></span>
                    </div>


                    <!-- Unavailability Calendar Section -->
                    <div class="unavailability-calendar">
                        <div class="unavailability-calendar-container">
                            <!-- Calendar Header -->
                            <div class="calendar-header">
                                <button type="button" id="prevMonthBtn" class="calendar-nav-btn">
                                    <i class="fas fa-chevron-left"></i>
                                </button>
                                <div id="currentMonthYear" class="calendar-month-year"></div>
                                <button type="button" id="nextMonthBtn" class="calendar-nav-btn">
                                    <i class="fas fa-chevron-right"></i>
                                </button>
                            </div>

                            <!-- Calendar Grid -->
                            <div class="calendar-grid">
                                <div class="calendar-weekdays">
                                    <div class="calendar-weekday"><spring:message code="calendar.monday.short" /></div>
                                    <div class="calendar-weekday"><spring:message code="calendar.tuesday.short" /></div>
                                    <div class="calendar-weekday"><spring:message code="calendar.wednesday.short" /></div>
                                    <div class="calendar-weekday"><spring:message code="calendar.thursday.short" /></div>
                                    <div class="calendar-weekday"><spring:message code="calendar.friday.short" /></div>
                                    <div class="calendar-weekday"><spring:message code="calendar.saturday.short" /></div>
                                    <div class="calendar-weekday"><spring:message code="calendar.sunday.short" /></div>
                                </div>
                                <div id="calendarDays" class="calendar-days"></div>
                            </div>

                            <!-- Calendar Legend -->
                            <div class="calendar-legend">

                                <div class="legend-item">
                                    <div class="legend-color range-start"></div>
                                    <span><spring:message code="dashboard.availability.legend.rangeStart" /></span>
                                </div>
                                <div class="legend-item">
                                    <div class="legend-color range-end"></div>
                                    <span><spring:message code="dashboard.availability.legend.rangeEnd" /></span>
                                </div>
                                <div class="legend-item">
                                    <div class="legend-color in-range"></div>
                                    <span><spring:message code="dashboard.availability.legend.inRange" /></span>
                                </div>
                            </div>

                            <!-- Selection Info -->
                            <div id="selectionInfo" class="selection-info" style="display: none;">
                                <div class="selection-text">
                                    <i class="fas fa-calendar-day"></i>
                                    <span id="selectionText"></span>
                                </div>
                                <div class="selection-actions">
                                    <button type="button" class="btn btn-primary" onclick="confirmSelection()">
                                        <i class="fas fa-check"></i>
                                        <spring:message code="dashboard.availability.confirm" />
                                    </button>
                                    <button type="button" class="btn btn-secondary" onclick="cancelSelection()">
                                        <i class="fas fa-times"></i>
                                        <spring:message code="dashboard.availability.cancel" />
                                    </button>
                                </div>
                            </div>

                            <!-- Loading indicator -->
                            <div id="calendarLoading" class="calendar-loading" style="display: none;">
                                <i class="fas fa-spinner fa-spin"></i>
                                <span><spring:message code="dashboard.availability.loading" /></span>
                            </div>
                        </div>

                        <!-- Hidden container for form inputs -->
                        <div id="unavailability-inputs-container" style="display: none;">
                            <c:forEach items="${updateAvailabilityForm.unavailabilitySlots}" var="unavailability" varStatus="status">
                                <input type="hidden" name="unavailabilitySlots[${status.index}].startDate" value="${unavailability.startDate}" />
                                <input type="hidden" name="unavailabilitySlots[${status.index}].endDate" value="${unavailability.endDate}" />
                            </c:forEach>
                        </div>

                        <div id="unavailability-error" class="error-message" style="display: none; margin-bottom: 10px;"></div>
                        <div class="error-container">
                            <form:errors path="unavailabilitySlots" cssClass="error-message" element="div" />
                        </div>
                    </div>

                    <!-- Unified Submit Button -->
                    <button type="submit" class="btn-submit-doctor-availability" id="unified-save-button">
                        <i class="fas fa-save"></i> <spring:message code="dashboard.availability.saveChanges" />
                    </button>

                </form:form>
            </div>
        </div>
    </div>
</main>

<script src="<c:url value='/js/toast-notification.js' />"></script>
<script src="<c:url value='/js/unavailability-calendar.js' />"></script>

<script>
    // Global variables for office-dependent time slots
    let timeSlotCounter = 0;
    let availabilitySlots = [];

    // Load doctor offices data
    const doctorOffices = [
        <c:forEach items="${doctorOffices}" var="office" varStatus="status">
        {
            id: ${office.id},
            name: "${office.officeName}",
            index: ${status.index}
        }<c:if test="${!status.last}">,</c:if>
        </c:forEach>
    ];

    // Localized month names from server
    const monthNames = [
        '<spring:message code="month.january" javaScriptEscape="true" />',
        '<spring:message code="month.february" javaScriptEscape="true" />',
        '<spring:message code="month.march" javaScriptEscape="true" />',
        '<spring:message code="month.april" javaScriptEscape="true" />',
        '<spring:message code="month.may" javaScriptEscape="true" />',
        '<spring:message code="month.june" javaScriptEscape="true" />',
        '<spring:message code="month.july" javaScriptEscape="true" />',
        '<spring:message code="month.august" javaScriptEscape="true" />',
        '<spring:message code="month.september" javaScriptEscape="true" />',
        '<spring:message code="month.october" javaScriptEscape="true" />',
        '<spring:message code="month.november" javaScriptEscape="true" />',
        '<spring:message code="month.december" javaScriptEscape="true" />'
    ];

    // Localized messages
    const messages = {
        confirmDelete: '<spring:message code="dashboard.availability.confirmDelete" javaScriptEscape="true" />',
        deleteSuccess: '<spring:message code="dashboard.availability.deleteSuccess" javaScriptEscape="true" />',
        addSuccess: '<spring:message code="dashboard.availability.addSuccess" javaScriptEscape="true" />',
        errorOccurred: '<spring:message code="dashboard.availability.errorOccurred" javaScriptEscape="true" />',
        selectStartDate: '<spring:message code="dashboard.availability.selectStartDate" javaScriptEscape="true" />',
        selectEndDate: '<spring:message code="dashboard.availability.selectEndDate" javaScriptEscape="true" />',
        selectedRange: '<spring:message code="dashboard.availability.selectedRange" javaScriptEscape="true" />',
        deleteTitle: '<spring:message code="dashboard.availability.deleteTitle" javaScriptEscape="true" />',
        until: '<spring:message code="dashboard.availability.until" javaScriptEscape="true" />',
        office: '<spring:message code="register.office" javaScriptEscape="true" />',
        dayOfWeek: '<spring:message code="register.dayOfWeek" javaScriptEscape="true" />',
        startTime: '<spring:message code="register.startTime" javaScriptEscape="true" />',
        endTime: '<spring:message code="register.endTime" javaScriptEscape="true" />',
        monday: '<spring:message code="register.monday" javaScriptEscape="true" />',
        tuesday: '<spring:message code="register.tuesday" javaScriptEscape="true" />',
        wednesday: '<spring:message code="register.wednesday" javaScriptEscape="true" />',
        thursday: '<spring:message code="register.thursday" javaScriptEscape="true" />',
        friday: '<spring:message code="register.friday" javaScriptEscape="true" />',
        saturday: '<spring:message code="register.saturday" javaScriptEscape="true" />',
        sunday: '<spring:message code="register.sunday" javaScriptEscape="true" />',
        timeSlotInvalidTime: '<spring:message code="register.timeSlotInvalidTime" javaScriptEscape="true" />',
        timeSlotOverlap: '<spring:message code="register.timeSlotOverlap" javaScriptEscape="true" />',
        timeSlotRequired: '<spring:message code="register.timeSlotRequired" javaScriptEscape="true" />',
        noOfficesForSlot: '<spring:message code="register.noOfficesForSlot" javaScriptEscape="true" />'
    };

    // Context path for AJAX requests
    const contextPath = '${pageContext.request.contextPath}';

    document.addEventListener('DOMContentLoaded', function() {
        console.log('DOM loaded, initializing...');

        initializeTimeSlots();

        // Initial validation of slots
        validateTimeSlots();

        // Check if availability was updated successfully
        const urlParams = new URLSearchParams(window.location.search);
        if (urlParams.get('updated') === 'true') {
            showSuccessToast();

            // Remove the query parameter without refreshing the page
            const newUrl = window.location.pathname;
            window.history.replaceState({}, document.title, newUrl);
        }

        // Add form submission handler
        const availabilityForm = document.getElementById('updateAvailabilityForm');
        if (availabilityForm) {
            availabilityForm.addEventListener('submit', (e) => {
                if (!areTimeSlotsValid()) {
                    e.preventDefault();
                    return false;
                }

                // Create hidden inputs for office-dependent slots
                createTimeSlotHiddenInputs();
                return true;
            });
        }

        console.log('Initialization complete. TimeSlotCounter:', timeSlotCounter);
    });

    // Initialize time slots from existing office availability data
    function initializeTimeSlots() {
        console.log('Initializing time slots...');
        availabilitySlots = [];

        // Load existing slots from doctorOfficeAvailability
        <c:forEach items="${doctorOfficesAvailability}" var="officeSlot" varStatus="status">
        availabilitySlots.push({
            id: timeSlotCounter++,
            slotId: ${officeSlot.id},
            officeId: ${officeSlot.office.id},
            day: ${officeSlot.dayOfWeek},
            startTime: '${officeSlot.startTime}',
            endTime: '${officeSlot.endTime}'
        });
        </c:forEach>

        // Render all existing slots
        renderAllTimeSlots();

        // Update UI
        updateNoSlotsMessage();
        console.log('Time slots initialized:', availabilitySlots);
    }

    // Render all time slots
    function renderAllTimeSlots() {
        const container = document.getElementById('time-slot-inputs');
        if (container) {
            container.innerHTML = '';
        }

        availabilitySlots.forEach(slot => {
            renderTimeSlot(slot);
        });

        validateTimeSlots();
    }

    // Add a new time slot (like in register)
    function addTimeSlotRow() {
        console.log('Adding time slot row...');

        // Check if we have at least one office
        if (doctorOffices.length === 0) {
            showTimeSlotError(messages.noOfficesForSlot || "Please add at least one office before creating time slots");
            return;
        }

        // Create new slot with default values
        const newSlot = {
            id: timeSlotCounter++,
            slotId: null, // New slot, no ID yet
            officeId: doctorOffices[0].id, // Default to first office
            day: 0, // Monday
            startTime: "09:00",
            endTime: "17:00"
        };

        // Add to array
        availabilitySlots.push(newSlot);

        // Render the new slot
        renderTimeSlot(newSlot);

        // Update UI
        updateNoSlotsMessage();

        // Check for overlaps
        validateTimeSlots();
    }

    // Render a single time slot (following register pattern)
    function renderTimeSlot(slot) {
        const container = document.getElementById('time-slot-inputs');
        if (!container) return;

        // Create row
        const row = document.createElement('div');
        row.className = 'time-slot-row';
        row.id = `time-slot-` + slot.id;
        row.dataset.slotId = slot.id;

        // Create office select container
        const officeContainer = document.createElement('div');
        officeContainer.className = 'office-select';

        const officeLabel = document.createElement('label');
        officeLabel.className = 'time-label';
        officeLabel.textContent = messages.office || 'Office';
        officeContainer.appendChild(officeLabel);

        const officeSelect = document.createElement('select');
        officeSelect.className = 'form-control slot-office';
        officeSelect.dataset.slotId = slot.id;

        // Add office options
        doctorOffices.forEach(office => {
            const option = document.createElement('option');
            option.value = office.id;
            option.textContent = office.name || `Office `+ (office.index + 1);
            officeSelect.appendChild(option);
        });

        // Set selected office
        officeSelect.value = slot.officeId;

        // Add change event
        officeSelect.addEventListener('change', function() {
            updateTimeSlot(slot.id, 'officeId', Number.parseInt(this.value, 10));
        });

        officeContainer.appendChild(officeSelect);

        // Create day select container
        const dayContainer = document.createElement('div');
        dayContainer.className = 'day-select';

        const dayLabel = document.createElement('label');
        dayLabel.className = 'time-label';
        dayLabel.textContent = messages.dayOfWeek || 'Day of Week';
        dayContainer.appendChild(dayLabel);

        const daySelect = document.createElement('select');
        daySelect.className = 'form-control slot-day';
        daySelect.dataset.slotId = slot.id;

        const days = [
            { value: 0, text: messages.monday || 'Monday' },
            { value: 1, text: messages.tuesday || 'Tuesday' },
            { value: 2, text: messages.wednesday || 'Wednesday' },
            { value: 3, text: messages.thursday || 'Thursday' },
            { value: 4, text: messages.friday || 'Friday' },
            { value: 5, text: messages.saturday || 'Saturday' },
            { value: 6, text: messages.sunday || 'Sunday' }
        ];

        days.forEach(day => {
            const option = document.createElement('option');
            option.value = day.value;
            option.textContent = day.text;
            daySelect.appendChild(option);
        });

        // Set selected day
        daySelect.value = slot.day;

        // Add change event
        daySelect.addEventListener('change', function() {
            updateTimeSlot(slot.id, 'day', Number.parseInt(this.value, 10));
        });

        dayContainer.appendChild(daySelect);

        // Create start time select container
        const startContainer = document.createElement('div');
        startContainer.className = 'time-select';

        const startLabel = document.createElement('label');
        startLabel.className = 'time-label';
        startLabel.textContent = messages.startTime || 'Start Time';
        startContainer.appendChild(startLabel);

        const startSelect = document.createElement('select');
        startSelect.className = 'form-control slot-start';
        startSelect.dataset.slotId = slot.id;

        // Create end time select container
        const endContainer = document.createElement('div');
        endContainer.className = 'time-select';

        const endLabel = document.createElement('label');
        endLabel.className = 'time-label';
        endLabel.textContent = messages.endTime || 'End Time';
        endContainer.appendChild(endLabel);

        const endSelect = document.createElement('select');
        endSelect.className = 'form-control slot-end';
        endSelect.dataset.slotId = slot.id;

        // Add time options to both selects
        const timeOptions = getTimeOptions();

        timeOptions.forEach(time => {
            const startOption = document.createElement('option');
            startOption.value = time.value;
            startOption.textContent = time.display;
            startSelect.appendChild(startOption);

            const endOption = document.createElement('option');
            endOption.value = time.value;
            endOption.textContent = time.display;
            endSelect.appendChild(endOption);
        });

        // Set selected times
        startSelect.value = slot.startTime;
        endSelect.value = slot.endTime;

        // Add change events
        startSelect.addEventListener('change', function() {
            updateTimeSlot(slot.id, 'startTime', this.value);
        });

        endSelect.addEventListener('change', function() {
            updateTimeSlot(slot.id, 'endTime', this.value);
        });

        startContainer.appendChild(startSelect);
        endContainer.appendChild(endSelect);

        // Create remove button
        const removeBtn = document.createElement('button');
        removeBtn.type = 'button';
        removeBtn.className = 'btn-remove';
        removeBtn.textContent = '×';
        removeBtn.setAttribute('aria-label', 'Remove time slot');
        removeBtn.dataset.slotId = slot.id;

        removeBtn.addEventListener('click', () => {
            removeTimeSlot(slot.id);
        });

        // Add all elements to row (office first, like in register)
        row.appendChild(officeContainer);
        row.appendChild(dayContainer);
        row.appendChild(startContainer);
        row.appendChild(endContainer);
        row.appendChild(removeBtn);

        // Add row to container with animation
        row.style.opacity = '0';
        row.style.transform = 'translateY(10px)';
        container.appendChild(row);

        // Trigger animation
        setTimeout(() => {
            row.style.opacity = '1';
            row.style.transform = 'translateY(0)';
        }, 10);
    }

    // Get time options for selects (8 AM to 8 PM)
    function getTimeOptions() {
        const options = [];
        for (let hour = 8; hour <= 20; hour++) {
            const hourFormatted = hour < 10 ? `0`+hour : hour.toString();
            const hourDisplay = hour % 12 || 12;
            const ampm = hour < 12 ? 'AM' : 'PM';

            options.push({
                value: hourFormatted+`:00`,
                display: hourDisplay+`:00 `+ampm
            });
        }
        return options;
    }

    // Update a time slot property
    function updateTimeSlot(slotId, property, value) {
        const slotIndex = availabilitySlots.findIndex(slot => slot.id === slotId);

        if (slotIndex !== -1) {
            availabilitySlots[slotIndex][property] = value;
            validateTimeSlots();
        }
    }

    // Remove a time slot
    function removeTimeSlot(slotId) {
        const slotIndex = availabilitySlots.findIndex(slot => slot.id === slotId);

        if (slotIndex !== -1) {
            const row = document.getElementById(`time-slot-`+slotId);

            if (row) {
                // Animate removal
                row.style.opacity = '0';
                row.style.transform = 'translateY(-10px)';

                setTimeout(() => {
                    // Remove from DOM
                    if (row.parentNode) {
                        row.parentNode.removeChild(row);
                    }

                    // Remove from array
                    availabilitySlots.splice(slotIndex, 1);

                    // Update UI
                    updateNoSlotsMessage();

                    // Validate remaining slots
                    validateTimeSlots();

                    // Show warning
                    const warningElement = document.getElementById('trash-warning-availability');
                    if (warningElement) {
                        warningElement.style.display = 'block';
                    }
                }, 300);
            }
        }
    }

    // Validate all time slots for overlaps (same office + same day)
    function validateTimeSlots() {
        // Clear previous errors
        clearTimeSlotErrors();

        let hasErrors = false;

        // Check each slot
        availabilitySlots.forEach(slot => {
            const row = document.getElementById(`time-slot-`+slot.id);
            if (!row) return;

            // Check if end time is after start time
            if (slot.startTime >= slot.endTime) {
                markSlotError(row);
                showTimeSlotError(messages.timeSlotInvalidTime || 'End time must be after start time');
                hasErrors = true;
                return;
            }

            // Check for overlaps with other slots in the SAME office and SAME day
            const overlaps = availabilitySlots.filter(otherSlot => {
                // Skip comparing with self
                if (otherSlot.id === slot.id) return false;

                // Only check slots in the same day
                if (otherSlot.day !== slot.day) return false;

                // Check for time overlap
                return !(slot.endTime < otherSlot.startTime || slot.startTime > otherSlot.endTime);
            });

            if (overlaps.length > 0) {
                // Mark this slot as error
                markSlotError(row);

                // Mark overlapping slots as error
                overlaps.forEach(overlapSlot => {
                    const overlapRow = document.getElementById(`time-slot-`+overlapSlot.id);
                    if (overlapRow) {
                        markSlotError(overlapRow);
                    }
                });

                showTimeSlotError(messages.timeSlotOverlap || 'Time slots cannot overlap in the same office on the same day');
                hasErrors = true;
            }
        });

        // Update submit button state
        updateSaveButtonState();
        return !hasErrors;
    }

    // Show time slot error
    function showTimeSlotError(message) {
        const errorElement = document.getElementById('time-slot-error');
        if (errorElement) {
            errorElement.textContent = message;
            errorElement.style.display = 'block';
            errorElement.classList.add('visible');

            // Scroll to the error message
            errorElement.scrollIntoView({ behavior: 'smooth', block: 'center' });
        }
    }

    // Mark a slot row as having an error
    function markSlotError(row) {
        row.classList.add('slot-error');
    }

    // Clear all time slot errors
    function clearTimeSlotErrors() {
        const errorElement = document.getElementById('time-slot-error');
        if (errorElement) {
            errorElement.style.display = 'none';
            errorElement.classList.remove('visible');
        }

        const errorRows = document.querySelectorAll('.slot-error');
        errorRows.forEach(row => {
            row.classList.remove('slot-error');
        });
    }

    // Update the no slots message visibility
    function updateNoSlotsMessage() {
        const noSlotsMessage = document.getElementById('no-slots-message');
        if (noSlotsMessage) {
            noSlotsMessage.style.display = availabilitySlots.length === 0 ? 'block' : 'none';
        }

        updateSaveButtonState();
    }

    // Create hidden inputs for time slots before form submission (grouped by office)
    function createTimeSlotHiddenInputs() {
        const form = document.getElementById('updateAvailabilityForm');
        if (!form) return;

        // Remove any existing hidden inputs for office availability slots
        const existingInputs = document.querySelectorAll('input[name*="doctorOfficeAvailabilitySlots"]');
        existingInputs.forEach(input => {
            input.parentNode.removeChild(input);
        });

        // Group slots by office
        // const slotsByOffice = {};
        // availabilitySlots.forEach(slot => {
        //     if (!slotsByOffice[slot.officeId]) {
        //         slotsByOffice[slot.officeId] = [];
        //     }
        //     slotsByOffice[slot.officeId].push(slot);
        // });

        let index = 0;
        availabilitySlots.forEach(slot => {
            if (slot.slotId) {
                const slotIdInput = document.createElement('input');
                slotIdInput.type = 'hidden';
                slotIdInput.name = `doctorOfficeAvailabilitySlots[`+index+`].id`;
                slotIdInput.value = slot.slotId;
                form.appendChild(slotIdInput);
            }

            // Create office ID input
            const officeIdInput = document.createElement('input');
            officeIdInput.type = 'hidden';
            officeIdInput.name = `doctorOfficeAvailabilitySlots[`+index+`].officeId`;
            officeIdInput.value = slot.officeId;
            form.appendChild(officeIdInput);


            // Create day input
            const dayInput = document.createElement('input');
            dayInput.type = 'hidden';
            dayInput.name = `doctorOfficeAvailabilitySlots[`+index+`].dayOfWeek`;
            dayInput.value = slot.day;
            form.appendChild(dayInput);

            // Create start time input
            const startInput = document.createElement('input');
            startInput.type = 'hidden';
            startInput.name = `doctorOfficeAvailabilitySlots[`+index+`].startTime`;
            startInput.value = slot.startTime;
            form.appendChild(startInput);

            // Create end time input
            const endInput = document.createElement('input');
            endInput.type = 'hidden';
            endInput.name = `doctorOfficeAvailabilitySlots[`+index+`].endTime`;
            endInput.value = slot.endTime;
            form.appendChild(endInput);

            index++;
        })

        // Create hidden inputs for each office's slots
        // let officeIndex = 0;
        // Object.keys(slotsByOffice).forEach(officeId => {
        //     const slots = slotsByOffice[officeId];
        //
        //     slots.forEach((slot, slotIndex) => {
        //
        //         // Create slot ID input if exists
        //         if (slot.slotId) {
        //             const slotIdInput = document.createElement('input');
        //             slotIdInput.type = 'hidden';
        //             slotIdInput.name = `doctorOfficeAvailabilitySlots[`+officeIndex+`].officeAvailabilitySlotForms[`+slotIndex+`].id`;
        //             slotIdInput.value = slot.slotId;
        //             form.appendChild(slotIdInput);
        //         }
        //
        //         // Create office ID input
        //         const officeIdInput = document.createElement('input');
        //         officeIdInput.type = 'hidden';
        //         officeIdInput.name = `doctorOfficeAvailabilitySlots[`+officeIndex+`].officeId`;
        //         officeIdInput.value = officeId;
        //         form.appendChild(officeIdInput);
        //
        //
        //         // Create day input
        //         const dayInput = document.createElement('input');
        //         dayInput.type = 'hidden';
        //         dayInput.name = `doctorOfficeAvailabilitySlots[`+officeIndex+`].officeAvailabilitySlotForms[`+slotIndex+`].dayOfWeek`;
        //         dayInput.value = slot.day;
        //         form.appendChild(dayInput);
        //
        //         // Create start time input
        //         const startInput = document.createElement('input');
        //         startInput.type = 'hidden';
        //         startInput.name = `doctorOfficeAvailabilitySlots[`+officeIndex+`].officeAvailabilitySlotForms[`+slotIndex+`].startTime`;
        //         startInput.value = slot.startTime;
        //         form.appendChild(startInput);
        //
        //         // Create end time input
        //         const endInput = document.createElement('input');
        //         endInput.type = 'hidden';
        //         endInput.name = `doctorOfficeAvailabilitySlots[`+officeIndex+`].officeAvailabilitySlotForms[`+slotIndex+`].endTime`;
        //         endInput.value = slot.endTime;
        //         form.appendChild(endInput);
        //     });
        //
        //     officeIndex++;
        // });
    }

    // Check if time slots are valid for form submission
    function areTimeSlotsValid() {
        // Must have at least one time slot
        if (availabilitySlots.length === 0) {
            showTimeSlotError(messages.timeSlotRequired || 'At least one time slot is required');
            return false;
        }

        // No slots should have errors
        const errorSlots = document.querySelectorAll('.slot-error');
        return errorSlots.length === 0;
    }

    // Update save button state
    function updateSaveButtonState() {
        const saveButton = document.getElementById('unified-save-button');
        const hasErrors = document.querySelectorAll('.slot-error').length > 0;

        if (saveButton) {
            saveButton.disabled = hasErrors;
            if (hasErrors) {
                saveButton.classList.add('btn-disabled');
            } else {
                saveButton.classList.remove('btn-disabled');
            }
        }
    }
</script>
</body>
</html>
