#datasource.url=jdbc:postgresql://localhost/vitae2
#datasource.username=smaffeo33
#datasource.password=smaffeo
#datasource.url=jdbc:postgresql://localhost/vitae_backup
#datasource.username=nachopedemonte
#datasource.password=pincha
#datasource.url=jdbc:postgresql://localhost/vitae
#datasource.username=aggalan
#datasource.password=aggalan
security.secret-file=webapp/src/main/resources/secret.key
mail.username=vitaepaw@gmail.com
mail.password=cknn xrna teqg hzdi
mail.port=587
mail.host=smtp.gmail.com
#app.base-url=http://pawserver.it.itba.edu.ar/paw-2025a-11
app.base-url=http://localhost:5173
datasource.url=jdbc:postgresql://localhost/paw-2025
datasource.username=josebenegaslynch
datasource.password=pincha
#datasource.url=jdbc:postgresql://10.16.1.110/paw-2025a-11
#datasource.username=paw-2025a-11
#datasource.password=hxf74mDPl





