#datasource.url=jdbc:postgresql://10.16.1.110/paw-2025a-11
#datasource.username=paw-2025a-11
#datasource.password=hxf74mDPl
#datasource.url=jdbc:postgresql://localhost/vitae_local
#datasource.username=nachopedemonte
#datasource.password=pincha
#datasource.url=jdbc:postgresql://localhost/vitae
#datasource.username=neax
#datasource.password=neax
datasource.url=jdbc:postgresql://localhost/vitae
datasource.username=smaffeo
datasource.password=Dub@i2012